### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by anjerodesu** [olmokramer/atom-minimap-codeglance#12]
[Enter steps to reproduce below:]
1. Enabling code glance
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [minimap-codeglance](https://github.com/olmokramer/atom-minimap-codeglance) package, v0.4.2
### Stack Trace

Uncaught TypeError: Cannot read property 'addEventListener' of undefined

```
At /Users/zyyx-angelo/.atom/packages/minimap-codeglance/lib/utils.js:5

TypeError: Cannot read property 'addEventListener' of undefined
    at addEventListener (/Users/zyyx-angelo/.atom/packages/minimap-codeglance/lib/utils.js:5:10)
    at Object.addMinimap (/Users/zyyx-angelo/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:93:7)
    at /Users/zyyx-angelo/.atom/packages/minimap-codeglance/lib/main.js:69:32
    at /Users/zyyx-angelo/.atom/packages/minimap/lib/main.coffee:288:18
    at Map.forEach (native)
    at Main.observeMinimaps (/Users/zyyx-angelo/.atom/packages/minimap/lib/main.coffee:287:15)
    at Object.activatePlugin (/Users/zyyx-angelo/.atom/packages/minimap-codeglance/lib/main.js:68:49)
    at Main.module.exports.PluginManagement.updatesPluginActivationState (/Users/zyyx-angelo/.atom/packages/minimap/lib/mixins/plugin-management.coffee:92:16)
    at /Users/zyyx-angelo/.atom/packages/minimap/lib/mixins/plugin-management.coffee:112:24
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:568:7)
```
### Commands

```
     -3:43.1.0 application:open (atom-text-editor.editor.is-focused)
  2x -1:39 core:backspace (atom-text-editor.editor.is-focused)
     -0:26.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "git-difftool",
      "git-plus",
      "package-sync",
      "ruby-test",
      "refactor",
      "wrap-guide"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "minimap-codeglance": {}
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.2.1
docblockr, v0.7.3
file-icons, v1.6.9
highlight-selected, v0.10.1
language-generic-config, v0.2.0
language-latex, v0.6.1
latex, v0.25.1
linter-javac, v1.2.0
minimap, v4.13.2
minimap-codeglance, v0.4.2
minimap-git-diff, v4.1.8
webbox-color, v0.5.8
wordcount, v2.3.0

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
Hi everyone, I'm sorry for the extremely late reply. As you have probably noticed I've stopped maintaining my Atom plugins a few years ago. I got very frustrated with how Atom was maintained and started ignoring all of my plugins. I'm sorry for that. I won't install Atom to test and mergeer PRs, but I'd be happy to transfer my repositories to anyone that wants to maintain any of my plugins. Again, I'm sorry.
