### ISSUE TITLE
Uncaught Error: Undefined screen line when clipping screen position

### ISSUE THREAD

**Issue by Spartibartfast** [olmokramer/atom-minimap-codeglance#15]
[Enter steps to reproduce below:]
1. Just moving my mouse over the minimap causes this... after update to 1.1.0

**Atom Version**: 1.1.0
**System**: Ubuntu 15.04
**Thrown From**: [minimap-codeglance](https://github.com/olmokramer/atom-minimap-codeglance) package, v0.4.2
### Stack Trace

Uncaught Error: Undefined screen line when clipping screen position

```
At /usr/share/atom/resources/app.asar/src/display-buffer.js:778

Error: Undefined screen line when clipping screen position
  at DisplayBuffer.module.exports.DisplayBuffer.clipScreenPosition (/usr/share/atom/resources/app.asar/src/display-buffer.js:766:15)
  at DisplayBuffer.module.exports.DisplayBuffer.bufferPositionForScreenPosition (/usr/share/atom/resources/app.asar/src/display-buffer.js:718:20)
  at TextEditor.module.exports.TextEditor.bufferPositionForScreenPosition (/usr/share/atom/resources/app.asar/src/text-editor.js:1139:33)
  at Object.scrollToMinimapOffset (/home/chris/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:145:62)
  at atom-text-editor-minimap.<anonymous> (/home/chris/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:93:14)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "python-isort",
      "sync-settings",
      "project-manager"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
autocomplete-python, v0.9.4
autocomplete-ruby, v0.1.0
color-picker, v2.0.13
emmet, v2.3.13
file-type-icons, v0.7.3
highlight-selected, v0.10.1
java-importer, v1.4.1
linter, v1.10.0
linter-gcc, v0.3.9
linter-xo, v0.8.0
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
open-recent, v3.0.0
pigments, v0.18.1
project-ring, v0.35.2
python-tools, v0.6.5
refactor, v0.6.0
remote-edit, v1.8.22
save-session, v0.15.7
set-syntax, v0.3.0

# Dev
No dev packages
```

**Comment by Michael-Thibault** [comment]
Same here:

#### Config

```
  core:
    themes: [
      "one-dark-ui"
      "one-dark-vivid-syntax"
    ]
    disabledPackages: [
      "atom-ctags"
      "python-tools"
      "atom-commander"
      "aligner"
      "aligner-python"
    ]
```

#### Installed Packages

```
/Users/mthibault/.atom/packages (43)
├── advanced-open-file@0.11.0
├── aligner@0.17.1
├── aligner-python@1.0.1
├── atom-alignment@0.12.1
├── atom-beautify@0.28.16
├── atom-commander@0.5.0
├── atom-ctags@4.4.0
├── atom-dark-fusion-syntax@0.7.0
├── autoclose-html@0.19.0
├── autocomplete-plus@2.23.0
├── autocomplete-python@0.9.4
├── block-comment-lines@0.2.4
├── build-tools@4.0.3
├── ctags-status@1.3.3
├── docblockr@0.7.3
├── file-icons@1.6.11
├── goto@1.7.1
├── highlight-selected@0.10.1
├── java-generator@2.0.0
├── language-mediawiki@2.0.0
├── language-minecraft-forge-cfg@0.1.2
├── linter@1.10.0
├── linter-javac@1.2.0
├── linter-python-pep8@0.2.0
├── merge-conflicts@1.3.6
├── minimap@4.16.0
├── minimap-bookmarks@0.1.0
├── minimap-codeglance@0.4.2
├── minimap-find-and-replace@4.3.2
├── minimap-git-diff@4.1.8
├── minimap-highlight-selected@4.3.1
├── minimap-linter@1.0.0
├── minimap-pigments@0.1.7
├── minimap-selection@4.3.1
├── one-dark-vivid-syntax@1.1.1
├── open-recent@4.0.0
├── pigments@0.18.1
├── python-tools@0.6.5
├── seti-syntax@0.4.1
├── seti-ui@0.8.0
├── slim-dark-ui@0.12.0
├── symbol-gen@1.0.0
└── todo-show@0.16.0
```

**Comment by olmokramer** [comment]
Thanks for the reports! This should be fixed in v0.4.3 that I just published. Please let me know if it works

**Comment by Michael-Thibault** [comment]
Just confirming it's been fixed. Cheers.

**Comment by Spartibartfast** [comment]
Fixed for me as well, thanks!
