### ISSUE TITLE
Uncaught Error: Undefined screen line when clipping screen position

### ISSUE THREAD

**Issue by krasnovpro** [olmokramer/atom-minimap-codeglance#16]
[Enter steps to reproduce below:]
1. Hover cursor on minimap.
2. Got error.

**Atom Version**: 1.2.0-beta0
**System**: Mac OS X 10.9.5
**Thrown From**: [minimap-codeglance](https://github.com/olmokramer/atom-minimap-codeglance) package, v0.4.2
### Stack Trace

Uncaught Error: Undefined screen line when clipping screen position

```
At /Applications/Dev/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:861

Error: Undefined screen line when clipping screen position
    at DisplayBuffer.module.exports.DisplayBuffer.clipScreenPosition (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:849:15)
    at DisplayBuffer.module.exports.DisplayBuffer.bufferPositionForScreenPosition (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:801:20)
    at TextEditor.module.exports.TextEditor.bufferPositionForScreenPosition (/Applications/Dev/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1191:33)
    at Object.scrollToMinimapOffset (/Users/oleg/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:142:28)
    at atom-text-editor-minimap.<anonymous> (/Users/oleg/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:88:14)
```
### Commands

```
     -0:14.4.0 editor:toggle-soft-wrap (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "newton-dark-ui",
      "newton-dark-syntax"
    ],
    "disabledPackages": [
      "metrics",
      "vim-mode"
    ],
    "packagesWithKeymapsDisabled": [
      "emmet",
      "last-cursor-position",
      "multi-cursor"
    ]
  },
  "minimap-codeglance": {
    "numberOfLines": 15,
    "hideLineNumbersInTypeWriter": false
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.10
atom-alignment, v0.12.1
atom-jade, v0.3.0
color-picker, v2.0.13
emmet, v2.3.13
language-apache, v1.3.0
language-nginx, v0.6.1
last-cursor-position, v0.9.0
linter, v1.10.0
linter-jade, v0.3.2
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.2
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
minimap-split-diff, v0.2.0
newton-dark-syntax, v1.1.5
newton-dark-ui, v1.0.9
pigments, v0.18.1
save-session, v0.15.7
set-syntax, v0.3.0
ult-terminal, v0.2.0

# Dev
No dev packages
```

**Comment by AsaAyers** [comment]
I'm on Atom 1.1 and I'm getting this error every time `atom-minimap-codeglance` attempts to open. http://blog.atom.io/2015/10/29/atom-1-1-is-out.html

**Comment by dander401** [comment]
I am on Atom 1.0.19 and I get this when I mouse over the minimap

**Comment by scherednychenko** [comment]
In Atom 1.1.0 this error occurs each time when you hover minimap by mouse. Seems it reacts on MouseOver event.

**Comment by olmokramer** [comment]
Thanks for the reports everyone!

It was actually the new version (4.16.0) of the minimap package that caused this. Some properties on the minimap object that codeglance relies upon had their name changed. I just published a new version that should fix this.

**Comment by scherednychenko** [comment]
@olmokramer FYI - just updated to version 0.4.3 - the issue is gone.

Thanks.

**Comment by diegognt** [comment]
Change the tab and then this appear, also when I hover the minimap

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [minimap-codeglance](https://github.com/olmokramer/atom-minimap-codeglance) package, v0.4.3

### Stack Trace

Uncaught Error: Undefined screen line when clipping screen position

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:778

Error: Undefined screen line when clipping screen position
    at DisplayBuffer.module.exports.DisplayBuffer.clipScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:766:15)
    at DisplayBuffer.module.exports.DisplayBuffer.bufferPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:718:20)
    at TextEditor.module.exports.TextEditor.bufferPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1139:33)
    at Object.scrollToMinimapOffset (/Users/perseus/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:142:28)
    at atom-text-editor-minimap.<anonymous> (/Users/perseus/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:88:14)
```

### Commands

```
     -4:25.3.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -4:25.3.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -4:24.2.0 core:save (atom-text-editor.editor.is-focused)
     -4:19.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:18.4.0 core:save (atom-text-editor.editor.is-focused)
  4x -4:06.9.0 core:undo (atom-text-editor.editor.is-focused)
     -3:59.5.0 core:save (atom-text-editor.editor.is-focused)
     -3:43.9.0 core:paste (atom-text-editor.editor.is-focused)
     -3:41.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:39.2.0 core:save (atom-text-editor.editor.is-focused)
     -3:01.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -3:01.3.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -3:00.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:58.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:16.4.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:09.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "chester-atom-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
angularjs, v0.3.3
angularjs-styleguide-snippets, v0.7.2
atom-beautify, v0.28.16
atom-jade, v0.3.0
atom-jasmine, v0.6.0
chester-atom-syntax, v0.1.1
color-picker, v2.0.13
docblockr, v0.7.3
jade-beautify, v0.0.11
js-refactor, v0.6.0
linter, v1.10.0
linter-csslint, v1.1.0
linter-handlebars, v2.2.0
linter-htmlhint, v0.2.1
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
linter-scss-lint, v2.4.0
minimap, v4.16.0
minimap-codeglance, v0.4.3
minimap-git-diff, v4.1.8
minimap-linter, v1.0.0
nucleus-dark-ui, v0.6.6
pigments, v0.18.1
refactor, v0.6.0

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
@diegognt Did you already try to reload Atom?

**Comment by scherednychenko** [comment]
It needs to be re-launched completely - I did it after I installed the update - and then it works fine.
