### ISSUE TITLE
Uncaught TypeError: atom.workspace.buildTextEditor is not a function

### ISSUE THREAD

**Issue by vitalii4reva** [olmokramer/atom-minimap-codeglance#17]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [minimap-codeglance](https://github.com/olmokramer/atom-minimap-codeglance) package, v0.4.4
### Stack Trace

Uncaught TypeError: atom.workspace.buildTextEditor is not a function

```
At /C:/Users/v.petrenko/.atom/packages/minimap-codeglance/lib/minimap-codeglance-element.js:28

TypeError: atom.workspace.buildTextEditor is not a function
  at minimap-codeglance.createdCallback (C:\Users\v.petrenko\.atom\packages\minimap-codeglance\lib\minimap-codeglance-element.js:28:33)
  at minimapCodeglanceElement (C:\Users\v.petrenko\.atom\packages\minimap-codeglance\lib\minimap-codeglance-element.js:126:19)
  at Object.initialize (C:\Users\v.petrenko\.atom\packages\minimap-codeglance\lib\minimap-codeglance.js:30:64)
  at minimapCodeglance (C:\Users\v.petrenko\.atom\packages\minimap-codeglance\lib\minimap-codeglance.js:172:35)
  at Object.activatePlugin (C:\Users\v.petrenko\.atom\packages\minimap-codeglance\lib\main.js:52:69)
  at Main.module.exports.PluginManagement.updatesPluginActivationState (C:\Users\v.petrenko\.atom\packages\minimap\lib\mixins\plugin-management.coffee:89:14)
  at C:\Users\v.petrenko\.atom\packages\minimap\lib\mixins\plugin-management.coffee:110:8
  at Config.module.exports.Config.observeKeyPath (C:\Users\v.petrenko\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:549:7)
  at Config.module.exports.Config.observe (C:\Users\v.petrenko\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:129:21)
  at Main.module.exports.PluginManagement.registerPluginControls (C:\Users\v.petrenko\.atom\packages\minimap\lib\mixins\plugin-management.coffee:109:49)
  at Main.module.exports.PluginManagement.registerPlugin (C:\Users\v.petrenko\.atom\packages\minimap\lib\mixins\plugin-management.coffee:42:6)
  at Object.consumeMinimapServiceV1 (C:\Users\v.petrenko\.atom\packages\minimap-codeglance\lib\main.js:39:18)
  at Provider.module.exports.Provider.provide (C:\Users\v.petrenko\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
  at C:\Users\v.petrenko\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "language-javascript-semantic",
      "symbols-tree-view",
      "symbols-view",
      "atom-gist"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-commander, v0.5.0
atom-ctags, v4.4.0
autocomplete-ctags, v0.3.2
ctags-status, v1.3.4
fancy-bracket-matcher, v0.4.1
file-icons, v1.6.11
git-diff-details, v0.21.0
git-log, v0.4.1
highlight-line, v0.11.0
javascript-object-snippets, v0.3.0
javascript-snippets, v1.0.0
language-babel, v2.0.2
language-javascript-jsx, v0.3.7
linter, v1.10.0
linter-eslint, v4.0.0
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.4
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
nuclide-flow, v0.0.32
pigments, v0.18.1
project-manager, v2.6.5
react-snippets, v0.2.0
redux-snippets, v0.2.1
refactor, v0.6.0
set-syntax, v0.3.0
seti-icons, v0.4.5
source-preview-react, v0.2.0
travis-ci-status, v0.18.0
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by chrissphinx** [comment]
Also occuring under OS X.
1. Start Atom with minimap and minimap-codeglance enabled
2. Error is thrown:

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [minimap-codeglance](https://github.com/olmokramer/atom-minimap-codeglance) package, v0.4.4

### Stack Trace

Uncaught TypeError: atom.workspace.buildTextEditor is not a function

```
At /Users/sphinx/.atom/packages/minimap-codeglance/lib/minimap-codeglance-element.js:16

TypeError: atom.workspace.buildTextEditor is not a function
    at minimap-codeglance.createdCallback (/Users/sphinx/.atom/packages/minimap-codeglance/lib/minimap-codeglance-element.js:16:33)
    at minimapCodeglanceElement (/Users/sphinx/.atom/packages/minimap-codeglance/lib/minimap-codeglance-element.js:117:19)
    at Object.initialize (/Users/sphinx/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:10:20)
    at minimapCodeglance (/Users/sphinx/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:154:35)
    at Object.activatePlugin (/Users/sphinx/.atom/packages/minimap-codeglance/lib/main.js:31:32)
    at Main.module.exports.PluginManagement.updatesPluginActivationState (/Users/sphinx/.atom/packages/minimap/lib/mixins/plugin-management.coffee:92:16)
    at /Users/sphinx/.atom/packages/minimap/lib/mixins/plugin-management.coffee:112:24
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:549:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:129:21)
    at Main.module.exports.PluginManagement.registerPluginControls (/Users/sphinx/.atom/packages/minimap/lib/mixins/plugin-management.coffee:110:55)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "vim-mode",
      "language-latex",
      "atom-beautify"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
minimap, v4.16.0
minimap-codeglance, v0.4.4

# Dev
No dev packages
```

**Comment by alferpal** [comment]
Started occuring after the upgrade:

[Enter steps to reproduce below:]
1. ... Update from v.0.4.3 to v0.4.4
2. ... Once updatet, on each atom start:

**Atom Version**: 1.1.0
**System**: linux 4.3.0-1-ARCH
**Thrown From**: [minimap-codeglance](https://github.com/olmokramer/atom-minimap-codeglance) package, v0.4.4

### Stack Trace

Uncaught TypeError: atom.workspace.buildTextEditor is not a function

```
At /home/akai/.atom/packages/minimap-codeglance/lib/minimap-codeglance-element.js:16

TypeError: atom.workspace.buildTextEditor is not a function
    at minimap-codeglance.createdCallback (/home/akai/.atom/packages/minimap-codeglance/lib/minimap-codeglance-element.js:16:33)
    at minimapCodeglanceElement (/home/akai/.atom/packages/minimap-codeglance/lib/minimap-codeglance-element.js:117:19)
    at Object.initialize (/home/akai/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:10:20)
    at minimapCodeglance (/home/akai/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:154:35)
    at Object.activatePlugin (/home/akai/.atom/packages/minimap-codeglance/lib/main.js:31:32)
    at Main.module.exports.PluginManagement.updatesPluginActivationState (/home/akai/.atom/packages/minimap/lib/mixins/plugin-management.coffee:89:14)
    at /home/akai/.atom/packages/minimap/lib/mixins/plugin-management.coffee:110:8
    at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app.asar/src/config.js:549:7)
    at Config.module.exports.Config.observe (/usr/share/atom/resources/app.asar/src/config.js:129:21)
    at Main.module.exports.PluginManagement.registerPluginControls (/home/akai/.atom/packages/minimap/lib/mixins/plugin-management.coffee:109:49)
    at Main.module.exports.PluginManagement.registerPlugin (/home/akai/.atom/packages/minimap/lib/mixins/plugin-management.coffee:42:6)
    at Object.consumeMinimapServiceV1 (/home/akai/.atom/packages/minimap-codeglance/lib/main.js:20:18)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:416:9)
    at process._tickCallback (node.js:345:13)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "audioBeep": false,
    "projectHome": "/home/akai/projects",
    "themes": [
      "seti-ui",
      "bandicoot"
    ],
    "disabledPackages": [
      "spell-check",
      "welcome",
      "language-ruby-on-rails",
      "language-ruby",
      "language-property-list",
      "language-perl",
      "language-objective-c",
      "language-mustache",
      "language-hyperlink",
      "language-go",
      "language-csharp",
      "language-coffee-script",
      "language-clojure",
      "eclipse-keybindings",
      "deprecation-cop",
      "dev-live-reload",
      "disable-keybindings",
      "language-source",
      "language-toml",
      "node-resolver",
      "save-session"
    ],
    "packagesWithKeymapsDisabled": [
      "git-diff",
      "notifications"
    ],
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

``` coffee
# User
atom-ternjs, v0.8.4
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
bandicoot, v0.0.6
editorconfig, v1.2.2
ember-snippets, v1.4.0
fonts, v1.0.0
language-diff, v0.3.1
language-docker, v1.1.3
language-javascript-better, v1.7.1
language-javascript-semantic, v0.2.1
linter, v1.10.0
linter-eslint, v4.0.0
minimap, v4.16.0
minimap-autohide, v0.10.1
minimap-codeglance, v0.4.4
minimap-find-and-replace, v4.3.2
minimap-linter, v1.0.0
minimap-selection, v4.3.1
project-manager, v2.6.5
seti-ui, v0.8.1

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
Thanks for the reports. I was using Atom v1.2 API that I thought was also present in v1.1. I'll publish a patch soon.

**Comment by sdaitzman** [comment]
Thanks :smile: looking forward to that patch.

**Comment by a7madgamal** [comment]
+1 for patch :D

**Comment by olmokramer** [comment]
Alright, it seems like it's working fine in Atom 1.1. I'm trying to publish the new version, but I'm having some difficulties. It'll probably be up in a few minutes.

**Comment by Michael-Thibault** [comment]
Confirming that the patch to 0.4.5 has fixed this problem on Atom 1.1, on OS X.

**Comment by sbrl** [comment]
Yep, that patch fixes it for me too.

**Comment by a7madgamal** [comment]
same here. thanks <3
But I had to restart Atom a few times after the update for it to work after updating!

**Comment by davisonio** [comment]
Looks like this is fixed :)
