### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by bean5** [olmokramer/atom-minimap-codeglance#2]
[Enter steps to reproduce below:]
1. Open mini map settings
2. Uncheck then recheck "codeglance"

**Atom Version**: 1.0.2
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [minimap-codeglance](https://github.com/olmokramer/atom-minimap-codeglance) package, v0.1.7
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\bean5\.atom\packages\minimap-codeglance\lib\minimap-codeglance.js:23

TypeError: undefined is not a function
  at Object.destroy (C:\Users\bean5\.atom\packages\minimap-codeglance\lib\minimap-codeglance.js:23:18)
  at Object.deactivatePlugin (C:\Users\bean5\.atom\packages\minimap-codeglance\lib\main.js:73:23)
  at Main.module.exports.PluginManagement.updatesPluginActivationState (C:\Users\bean5\.atom\packages\minimap\lib\mixins\plugin-management.coffee:92:14)
  at C:\Users\bean5\.atom\packages\minimap\lib\mixins\plugin-management.coffee:110:8
  at C:\Users\bean5\AppData\Local\atom\app-1.0.2\resources\app.asar\src\config.js:557:16
  at C:\Users\bean5\AppData\Local\atom\app-1.0.2\resources\app.asar\src\config.js:574:20
  at Emitter.module.exports.Emitter.emit (C:\Users\bean5\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\bean5\AppData\Local\atom\app-1.0.2\resources\app.asar\src\config.js:736:29)
  at Config.module.exports.Config.setRawValue (C:\Users\bean5\AppData\Local\atom\app-1.0.2\resources\app.asar\src\config.js:551:19)
  at Config.module.exports.Config.set (C:\Users\bean5\AppData\Local\atom\app-1.0.2\resources\app.asar\src\config.js:233:14)
  at Main.module.exports.PluginManagement.togglePluginActivation (C:\Users\bean5\.atom\packages\minimap\lib\mixins\plugin-management.coffee:68:19)
  at C:\Users\bean5\.atom\packages\minimap\lib\minimap-quick-settings-element.coffee:134:22
  at HTMLLIElement.<anonymous> (C:\Users\bean5\.atom\packages\minimap\lib\minimap-quick-settings-element.coffee:139:7)

```
### Commands

```
     -1:10.6.0 command-palette:toggle (atom-pane.pane.active)
     -1:06.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:06.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "open-last-project",
      "git-difftool",
      "background-matrix",
      "remember-session",
      "tab-rename",
      "language-coldfusion",
      "tab-rename"
    ]
  },
  "minimap-codeglance": {}
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
color-picker, v2.0.9
command-logger, v0.23.0
editor-stats, v0.17.0
file-type-icons, v0.7.0
hide-files, v0.1.7
last-cursor-position, v0.9.0
linter, v1.2.3
minimap, v4.11.1
minimap-codeglance, v0.1.7
minimap-git-diff, v4.1.4
open-recent, v2.2.4
recent-projects, v0.4.3
red-wavy-underline, v0.3.0

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
Oops, forgot to test that part. Thanks for submitting the issue! A new version is up that should fix this :)

**Comment by bean5** [comment]
Awesome. Atom rocks and you have helped it to be even better. Thanks for the fast response time!

**Comment by bean5** [comment]
(I closed this after testing the latest release. It is now working.)

**Comment by olmokramer** [comment]
Cool, thanks for letting me know :)
