### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by rm-code** [olmokramer/atom-minimap-codeglance#3]
1. Hover over the minimap

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [minimap-codeglance](https://github.com/olmokramer/atom-minimap-codeglance) package, v0.1.8
### Stack Trace

Uncaught TypeError: Cannot read property 'appendChild' of null

```
At /Users/Robert/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:84

TypeError: Cannot read property 'appendChild' of null
  at Object.attachElement (/Users/Robert/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:84:74)
  at Object.setCurrentMinimap (/Users/Robert/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:69:10)
  at atom-text-editor-minimap.<anonymous> (/Users/Robert/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:51:21)

```
### Commands

```
     -2:38.5.0 core:copy (input.hidden-input)
     -2:30 core:move-down (input.hidden-input)
  4x -2:30 core:move-up (input.hidden-input)
  2x -2:29 editor:newline (input.hidden-input)
     -2:25.2.0 autocomplete-plus:confirm (input.hidden-input)
     -2:23.6.0 core:paste (input.hidden-input)
     -2:22.9.0 core:backspace (input.hidden-input)
     -2:22 linter:set-bubble-transparent (input.hidden-input)
  2x -2:21.9.0 editor:move-to-beginning-of-word (input.hidden-input)
  2x -2:20.7.0 editor:select-to-beginning-of-word (input.hidden-input)
     -2:19.8.0 core:backspace (input.hidden-input)
     -2:18.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -2:17.9.0 editor:newline (input.hidden-input)
     -2:14 core:backspace (input.hidden-input)
     -2:13.2.0 editor:newline (input.hidden-input)
     -2:07.4.0 core:backspace (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "themes": [
      "base-16-ocean-dark-ui-theme",
      "base16-ocean-dark-syntax-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
base-16-ocean-dark-ui-theme, v1.4.0
base16-ocean-dark-syntax-theme, v0.1.5
file-icons, v1.5.8
git-diff-details, v0.18.0
language-lua, v0.9.4
language-moonscript, v1.7.0
linter, v1.2.3
linter-lua, v0.1.6
linter-lua-findglobals, v0.5.0
minimap, v4.11.2
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.1.8
minimap-git-diff, v4.1.5
project-manager, v1.15.11
wordcount, v2.2.2

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
Thanks for the report. Do you by any chance have the `useShadowDOM` setting disabled (in the editor section of the settings panel)? I thought that option had been removed for a long time, so I didn't add support for non-shadowDOM editors.

**Comment by rm-code** [comment]
The option is still there, but it is deactivated (`useShadowDOM: false` in config.cson).

**Comment by olmokramer** [comment]
Ah, does it work when you enable it?

**Comment by rm-code** [comment]
Yup, with this option enabled it works... sorry, my bad.

**Comment by olmokramer** [comment]
Thanks for confirming this :) I'll still have to add support for `useShadowDOM: false`, though.
