### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Kratos251189** [olmokramer/atom-minimap-codeglance#38]
[Enter steps to reproduce:]

1. Use a very long file ~130000 lines

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [minimap-codeglance](https://github.com/olmokramer/atom-minimap-codeglance) package 0.4.7

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:854

RangeError: Maximum call stack size exceeded
    at Object.spliceWithArray (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:362:52)
    at TokenizedBuffer.module.exports.TokenizedBuffer.bufferDidChange (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:278:24)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:692:42
    at Set.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:691:39)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:685:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:574:25)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:554:32
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:849:24)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:552:27)
    at TextBuffer.module.exports.TextBuffer.setText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:492:25)
    at TextEditor.module.exports.TextEditor.setText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1102:32)
    at /packages/minimap-codeglance/lib/minimap-codeglance-element.js:63:16)
    at Object.setCurrentMinimap (/packages/minimap-codeglance/lib/minimap-codeglance.js:111:18)
    at /packages/minimap-codeglance/lib/minimap-codeglance.js:75:14)
    at /packages/minimap-codeglance/lib/dom-listener.js:17:10)
```

### Commands

```
     -8:28.8.0 find-and-replace:show (input.hidden-input)
     -8:15.1.0 core:confirm (input.hidden-input)
     -0:53.8.0 find-and-replace:show (input.hidden-input)
     -0:53.5.0 core:paste (input.hidden-input)
     -0:52.5.0 core:confirm (input.hidden-input)
  5x -0:51.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-bootstrap4 1.4.0 
emmet 2.4.3 
minimap 4.28.2 
minimap-autohider 1.5.3 
minimap-codeglance 0.4.7 
platformio-ide-terminal 2.5.1 
project-manager 3.3.5 
rails-snippets 2.15.1 
rails-transporter 1.7.0 
symbols-tree-view 0.14.0 
```

**Comment by omeryagmurlu** [comment]
Any updates? This pops everytime I try to scroll using the minimap, which is way too often.
