### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clientHeight' of null

### ISSUE THREAD

**Issue by rm-code** [olmokramer/atom-minimap-codeglance#4]
1. Hover over the minimap

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [minimap-codeglance](https://github.com/olmokramer/atom-minimap-codeglance) package, v0.1.8
### Stack Trace

Uncaught TypeError: Cannot read property 'clientHeight' of null

```
At /Users/Robert/.atom/packages/minimap-codeglance/lib/minimap-codeglance-element.js:80

TypeError: Cannot read property 'clientHeight' of null
    at minimap-codeglance.getMaxOffsetY (/Users/Robert/.atom/packages/minimap-codeglance/lib/minimap-codeglance-element.js:80:27)
    at minimap-codeglance.translateY (/Users/Robert/.atom/packages/minimap-codeglance/lib/minimap-codeglance-element.js:68:29)
    at Object.scrollToMousePosition (/Users/Robert/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:126:18)
    at atom-text-editor-minimap.<anonymous> (/Users/Robert/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:53:21)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "base-16-ocean-dark-ui-theme",
      "base16-ocean-dark-syntax-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
base-16-ocean-dark-ui-theme, v1.4.0
base16-ocean-dark-syntax-theme, v0.1.5
file-icons, v1.5.8
git-diff-details, v0.18.0
language-lua, v0.9.4
language-moonscript, v1.7.0
linter, v1.2.3
linter-lua, v0.1.6
linter-lua-findglobals, v0.5.0
minimap, v4.11.2
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.1.8
minimap-git-diff, v4.1.5
project-manager, v1.15.11
wordcount, v2.2.2

# Dev
No dev packages
```

**Comment by rm-code** [comment]
This error occurs at the same time as issue #3. I wasn't sure if I should open separate tickets or just one since they are related.

**Comment by olmokramer** [comment]
Yeah, I think this is caused the same thing. I'll close this one when I know for sure.
