### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTextEditor' of undefined

### ISSUE THREAD

**Issue by anjerodesu** [olmokramer/atom-minimap-codeglance#8]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [minimap-codeglance](https://github.com/olmokramer/atom-minimap-codeglance) package, v0.2.3
### Stack Trace

Uncaught TypeError: Cannot read property 'getTextEditor' of undefined

```
At ~/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:98

TypeError: Cannot read property 'getTextEditor' of undefined
  at Object.getTextEditor (~/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:98:24)
  at Object.getTextEditorRoot (~/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:102:50)
  at Object.attachElement (~/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:107:31)
  at ~/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:55:14
  at HTMLBodyElement.<anonymous> (~/.atom/packages/minimap-codeglance/lib/utils.js:20:5)

```
### Commands

```
     -0:55.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:54.9.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:54.9.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:53.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:51.7.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:51.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:51.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:51.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:51.3.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:51.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:50.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.3.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
  2x -0:08.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:05.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:02.4.0 core:close (div.settings-view.pane-item)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "git-difftool",
      "git-plus",
      "package-sync",
      "ruby-test",
      "refactor",
      "git-diff",
      "jshint"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "minimap-codeglance": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.8
docblockr, v0.7.3
file-icons, v1.5.8
highlight-selected, v0.10.1
language-latex, v0.6.1
latex, v0.25.0
minimap, v4.12.1
minimap-codeglance, v0.2.3
minimap-git-diff, v4.1.7
wordcount, v2.2.2

# Dev
No dev packages
```

**Comment by lmartins** [comment]
Also started seeing this problem on my install after the last update. 
Unfortunately I had to disable the package as it would open error popups each time the mouse hovered the minimap area.

**Comment by olmokramer** [comment]
Hi, thanks for the reports. I just published a new version that should fix the crashes, but it introduces another bug: after switching the editor, the first time the codeglance view is showns it will be empty. I published the patch anyway, because it's the crashes are worse...

**Comment by olmokramer** [comment]
Ok, it seems that the content not showing is a bug in core. It also happens with old versions of this package that worked just fine a while ago.

**Comment by olmokramer** [comment]
I've rewritten a large part of the package, and now everything seems fine again. Don't really know what the issue was, but it seems to work :)

**Comment by anjerodesu** [comment]
I think it's safe to say that the issue has been resolved. Thanks. 🍻

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Version**: [minimap-codeglance](https://github.com/olmokramer/atom-minimap-codeglance) package, v0.4.0

**Comment by lmartins** [comment]
Started getting these error messages after todays update.

**Comment by olmokramer** [comment]
@lmartins Can you post the stack trace, please?

**Comment by lmartins** [comment]
Sure @olmokramer , here it goes:

```
TypeError: Cannot read property 'getTextEditor' of undefined
    at Object.getTextEditor (/Users/luismartins/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:120:24)
    at /Users/luismartins/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:100:17
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Minimap.module.exports.Minimap.destroy (/Users/luismartins/.atom/packages/minimap/lib/minimap.coffee:107:20)
    at /Users/luismartins/.atom/packages/minimap/lib/minimap.coffee:89:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:290:27)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:45:58)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:468:18)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:443:12)
```

**Comment by olmokramer** [comment]
Does this happen anytime you close a tab?

**Comment by olmokramer** [comment]
Ah, I think I understand what's going on... It should happen only when you haven't used codeglance (i.e. hovered the minimap) after starting atom and then close a tab/text editor, correct?

**Comment by olmokramer** [comment]
Ok, I think that should fix it. v0.4.2 will be up in a few minutes, please let me know if it's working alright :)

**Comment by lmartins** [comment]
Sorry, haven't had the opportunity to comment earlier but yeah, your description sounds like what was happening. Many thanks for the fix. 

Cheers.

**Comment by diegognt** [comment]
+1

**Comment by olmokramer** [comment]
@diegognt Are you saying that you're still getting this error?

**Comment by diegognt** [comment]
yes @olmokramer, unfortunately yes

**Comment by olmokramer** [comment]
@diegognt can you please post the stack trace of the error? And give some more details like when does this happen?

**Comment by diegognt** [comment]
Ok, let me recreated again

**Comment by kozzzmozz** [comment]
@olmokramer I recently receive these error message's after opening atom.
I tried reinstalling the minimap and the codeglance plugin, but without succes. At the moment I disabled codeglance and I don't receive any error message's anymore. Do you have any solution for this problem ?

Uncaught TypeError: Cannot read property 'style' of undefined

```
At /Users/Matthias/.atom/packages/minimap-codeglance/lib/minimap-codeglance-element.js:68

TypeError: Cannot read property 'style' of undefined
  at minimap-codeglance.showLineNumbers (/Users/Matthias/.atom/packages/minimap-codeglance/lib/minimap-codeglance-element.js:79:20)
  at /Users/Matthias/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:32:28
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:549:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:129:21)
  at Object.initialize (/Users/Matthias/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:31:66)
  at minimapCodeglance (/Users/Matthias/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:172:35)
  at Object.activatePlugin (/Users/Matthias/.atom/packages/minimap-codeglance/lib/main.js:52:69)
  at Main.module.exports.PluginManagement.updatesPluginActivationState (/Users/Matthias/.atom/packages/minimap/lib/mixins/plugin-management.coffee:89:14)
  at /Users/Matthias/.atom/packages/minimap/lib/mixins/plugin-management.coffee:110:8
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:549:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:129:21)
  at Main.module.exports.PluginManagement.registerPluginControls (/Users/Matthias/.atom/packages/minimap/lib/mixins/plugin-management.coffee:109:49)
  at Main.module.exports.PluginManagement.registerPlugin (/Users/Matthias/.atom/packages/minimap/lib/mixins/plugin-management.coffee:42:6)
  at Object.consumeMinimapServiceV1 (/Users/Matthias/.atom/packages/minimap-codeglance/lib/main.js:39:18)
  at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```

**Comment by olmokramer** [comment]
@mmmMatthias I think your issue is not the same as this one but rather #18. I think I've found a solution, but now I'm having issues publishing a new version. It should be up in a few minutes, though :)

**Comment by kozzzmozz** [comment]
@olmokramer It seems to be working well now, thank you for the effort. If I notice anything else in the future I will inform you. Keep up your great work. All the best !

**Comment by olmokramer** [comment]
Glad to hear that @mmmMatthias! And thank you for the kind words :)
